.image_python: &image_python 
    image: python:3

image: docker:latest

services:
  - docker:dind

stages:
  - report
  - bot
  - build
  - test
  - publish

before_script:
  - apk add bash git

build:
  stage: build
  script:
    - /bin/bash .utilities/check.sh
    - /bin/bash -e .utilities/build.sh
  only:
    - tags
  artifacts:
    paths:
      - "$CI_PROJECT_NAME.tar"

build:description_template:
  image: python:3.8-alpine
  stage: build
  script: sh -e .utilities/templates/templater.sh
  only:
    - tags
  artifacts:
    paths:
      - "*.description"

test:
  stage: test
  script: /bin/bash -e .utilities/test.sh
  only:
    - tags
  artifacts:
    paths:
      - "$CI_PROJECT_NAME.tar"

publish:
  stage: publish
  script: /bin/bash -e .utilities/publish.sh
  only:
    - tags
  artifacts:
    paths:
      - "$CI_PROJECT_NAME.tar"

bot:update_special_files_on_merge_request_approval:
  <<: *image_python
  stage: bot
  before_script:
    - pip install -r .ci/bot/update_special_files/requirements.txt
    - cd .ci/
  script: python -m bot.update_special_files ..
  rules:
    - if: '$CI_PIPELINE_SOURCE == "trigger" && $MERGE_REQUEST_ACTION == "approval"'

#update_docker_hub_full_description:
#  stage: publish
#  script: /bin/bash -e .utilities/update-docker-hub-full-description.sh
#  only:
#    - master

bot:package_update_notification:
  stage: report
  script: bash -e .utilities/package_update_notifier.sh
  only:
    - schedules
    # see https://docs.gitlab.com/ce/ci/yaml/README.html#onlyexcept-advanced for feature updates
    # refs:
    #   - schedules
    # variables:
    #   - $SCHEDULE_ID == $PACKAGE_UPDATE_NOTIFICATION_SCHEDULE_ID